### PR TITLE
Display milliseconds, matching given labels

### PR DESCRIPTION
**Pull request by indirect**
The [ActiveSupport::Notifications::Event class](https://github.com/rails/rails/blob/76489d81ba77216271870e11fba6889088016fa5/activesupport/lib/active_support/notifications/instrumenter.rb#L120-L134) states that times are stored in milliseconds. Based on the label `ms` in [badge.html.erb](https://github.com/hschne/rails-mini-profiler/blob/main/app/views/rails_mini_profiler/badge.html.erb#L36) and [profiled_requests/show.html.erb](https://github.com/hschne/rails-mini-profiler/blob/main/app/views/rails_mini_profiler/profiled_requests/show.html.erb#L17), I would expect the numbers show next to those labels to also be milliseconds. However, what is actually stored is microseconds, calculated by multiplying the `Event` millisecond values by 100,000 in [tracer.rb](https://github.com/hschne/rails-mini-profiler/blob/main/lib/rails_mini_profiler/tracers/tracer.rb#L31-L32). As a result, the numbers shown next to the label `ms` are actually µs instead. To fix this, we need to match the multiplication and division. That's what this PR does.

To demonstrate that rails-mini-profiler is actually multiplying by too much, here is a screenshot of the badge and the Rails log next to each other, showing that the Rails log shows 16ms while rails-mini-profiler shows 17,000ms.

Screen Shot 2022-02-08 at 10 53 21 PM

### CODE REVIEW

**Comment by hschne** [comment]
@indirect Thanks so much for your PR! And for fixing my typos and updating the documentation too! Amazing stuff! :clap: 

I'll give this a brief test later today, but just looking at the code everything looks great, so you can expect this to be merged pretty soon :+1:

**Comment by indirect** [comment]
Oops, I didn't see your comment about the commit linter, so I added a rake task to run all 4 linters and updated the commitment config to allow long links in commit footers 😅 Feel free to adjust to your taste when you merge, you can push to my branch before you merge. Thanks!

**Comment by hschne** [comment]
@indirect Alright, I had a look, and this appears to be more troublesome than expected, unfortunately. I'll go out on a limb here and say you found this issue using Rails 7? :sweat_smile: 

It appears that Rails 7 changed `event.time` and `event.end` from using microseconds to using milliseconds, which affects the calculations RMP makes for displaying durations. Check this out: 

```
=> event.time # Rails 7.0
6038925.450784
=> event.time # Rails 6.1
6081.814695554 
```

I believe that [this commit](https://github.com/rails/rails/commit/81d0dc90becfe0b8e7f7f26beb66c25d84b8ec7f) is responsible. Using your changes with Rails 7 gives me accurate measurements, but using them with Rails 6 gives me the wrong durations. I switched between [a new branch for Rails 7](https://github.com/hschne/rails-mini-profiler/compare/main...22-02-use-rails-7-as-default) and `main` to test this out.

I think it's good to just change `start` and `finish` to use millisecond timestamps (like you did) and just use `event.duration` (which always was in milliseconds) for the duration. Not sure why I didn't do that in the first place :thinking: 

I'd love to get your feedback on this. If it checks out, I'd merge your PR, and then later make the required changes to fix things up for earlier versions of Rails.

What do you say? :slightly_smiling_face:

**Comment by indirect** [comment]
@hschne lol oh no of course they did 🤦🏻 `event.duration` sounds like the way to go! in the newly-found tradition of making this PR as excessive as possible, I have added an appraisal for Rails 7, and added a test that checks a trace against an actual event generated by ActiveSupport::Instrumentation, to make sure things stay the same across versions.

**Pull request merged**
